services:
  web:
    build: .
    container_name: dujiaoka
    ports:
      - "8111:80"
    volumes:
      - ./data/uploads:/app/public/uploads
    environment:
      # Web 服务器配置
      WEB_DOCUMENT_ROOT: "/app/public"
      TZ: Asia/Shanghai

      # 应用配置
      APP_URL: "http://localhost:8111"
      APP_HTTPS: "false"
      APP_ENV: "local"
      APP_DEBUG: "true"

      # 后台配置
      ADMIN_ROUTE_PREFIX: "admin"
      ADMIN_LANGUAGE: "zh_CN"

    tty: true
    restart: always
    networks:
      - dujiaoka

networks:
  dujiaoka:
    driver: bridge
